switch (randBetween(0, 45)) {
                case 0: return "Tolles Foto, mein Freund" + first + "!";
                case 1: return "Was für ein tolles Foto" + first + "!";
                case 2: return "Tolle Arbeit! Sehr inspirierend" + first;
                case 3: return "Tolle Komposition, gut gemacht" + first + "!";
                case 4: return "Perfekt gemacht" + first + ".";
                case 5: return "Tolles Foto. Gut gemacht" + first + "!";
                case 6: return "Sehr schön. Gut gemacht" + first + "!";
                case 7: return "Schön gemacht" + first + "!";
                case 8: return "Exzellentes Foto" + first;
                case 9: return "Hervorragende Arbeit, mein Freund!";
                case 10: return "Genial! Gut gemacht" + first + ".";
                case 11: return "Sehr gut" + first + "!";
                case 12: return "Wunderschöne Aufnahme" + first;
                case 13: return "Wunderschön aufgenommenes Foto" + first + "!";
                case 14: return "Fantastisch! Dies ist ein tolles Foto" + first + ".";
                case 15: return "Außergewöhnliche Qualität" + first;
                case 16: return "Geniale Arbeit, mein Freund" + first + "!";
                case 17: return "Spektakuläres Foto" + first + "!";
                case 18: return "Fabelhafte Arbeit" + first + "!";
                case 19: return "Geniales Foto" + first + "!";
                case 20: return "Erstaunliches Foto" + first + "!";
                case 21: return "Hervorragende Arbeit" + first + "!";
                case 22: return "Großartig" + first + "!";

                case 23: return "Beeindruckende Komposition" + first + "!";
                case 24: return "Tolles Foto" + first + "!";
                case 25: return "Schöne Arbeit" + first + "!";
                case 26: return "Wunderschöne Komposition" + first + "!";
                case 27: return "Brillant" + first + "!";
                case 28: return "Tolles Foto" + first + "!";
                case 29: return "Gut gemacht" + first + "!";
                case 30: return "Schön" + first + "!";
                case 31: return "Ausgezeichnet" + first;
                case 32: return "Ausgezeichnete Arbeit" + first;
                case 33: return "Ausnahmsweise" + first + "!";
                case 34: return "Gute Arbeit" + first + "!";
                case 35: return "Spektakuläre Aufnahme" + first;
                case 36: return "Großartige Aufnahme" + first + "!";
                case 37: return "Tolles Foto" + first + ".";
                case 38: return "Gute Arbeit" + first + "!";
                case 39: return "Fantastisches Bild" + first + "!";
                case 40: return "Schönes Foto" + first + "!";
                case 41: return "Schönes Foto" + first + "!";
                case 42: return "Gut gemacht" + first + "!";
                case 43: return "Atemberaubend" + first + "!";
                case 44: return "Hervorragend" + first + "!";
                case 45: return "Großartige Arbeit" + first + "!";

            }